spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DB_NAME:microblog}
    username: ${DB_USER:root}
    password: ${DB_USER_PWD:root}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  application:
    name: Microblog

server:
  port: 8080
  servlet:
    context-path: "/api"