spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USER:root}
    password: ${DB_USER_PWD:root}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  application:
    name: ${APP_NAME:Microblog}

  redis:
    host: localhost
    port: 6379

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: "/api"

app:
  jwt:
    secretKey: ${JWT_SECRET_KEY:Zw1dsOA1hqSKlX9PVREovrt2S0h8AydmIvb4FwC/Ij4=}
    expiration: ${JWT_SECRET_EXPIRATION:86400000}
    issuer: ${JWT_SECRET_ISSUER:microblog}